### ISSUE TITLE
API Key Doesn't get Copied at Once

### ISSUE THREAD

**Issue by dhruvchandak30** [weatherapicom/javascript#1]
On the Dashboard Page 
The copy API key Button does not copy the key at once.

**Comment by ferdnyc** [comment]
I'm _sure_ this was the wrong place to post this, since it's an issue with the weatherapi.com website, not with the JavaScript API.

However, @dhruvchandak30's report does appear to be accurate. Testing with Google Chrome version 126.0.6478.114 on Linux, it takes _two_ clicks on the "Copy" button at https://www.weatherapi.com/my/ to successfully copy the API key. On the first click, nothing happens. The second click causes the button text to change to "Copied", and the API key is successfully placed in the clipboard.

**Comment by weatherapicom** [comment]
We have found the bug and have issued an update. 
 
Thanks for letting us know about the issue.

**Comment by ferdnyc** [comment]
Wow, that was _fast_! Thanks, @weatherapicom!

(I reported this to the Weather API team on July 2, using the contact form on the website, after realizing this issue was never going to be spotted since it was in the wrong place. They had it fixed in under a week.)

**Comment by dhruvchandak30** [comment]
Where is the active Repository? I want to contribute.
@weatherapicom

**Comment by ferdnyc** [comment]
@dhruvchandak30 For their website? I doubt they have a public one, the company website isn't part of the open-source offerings.
